version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 20000:27017